version: '3.7'

services:
  python_test:
    build: .

    command: [ "python", "./main.py" ]

    environment:
      PYTHONUNBUFFERED: 1

    image: test-python

    volumes:
      - '.:/app'

    working_dir: /app
