version: '3.7'

services:
  python_test:
    build: .

    command: [ "python", "./main.py" ]

    environment:
      PYTHONUNBUFFERED: 1

    image: test-python

    volumes:
      - '.:/usr/src/test/'

    working_dir: /usr/src/test/
  unit_test:
    build: .

    command: [ "pytest -vv" ]

    environment:
      PYTHONUNBUFFERED: 1

    image: test-python

    volumes:
      - '.:/usr/src/test/'

    working_dir: /usr/src/test/
