name: Dockerizing and Deployment

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - "release"
      - "master"

jobs:
  Dockerx:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-unit-web-app:${{github.run_number}}